# Generated by hand for TanPit ratio orders

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="RatioOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("order_no", models.IntegerField()),
                ("grease_percent", models.FloatField()),
                ("created_by", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_by", models.CharField(blank=True, default="", max_length=64)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratio_orders",
                        to="pits.pit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ratioorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("voided_at__isnull", True)),
                fields=("pit", "order_no"),
                name="uniq_active_ratio_order_no",
            ),
        ),
    ]
