# Generated by hand for TanPit 加脂配比单

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MixSlip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("seq", models.IntegerField()),
                ("fat_percent", models.FloatField()),
                ("created_by", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_by", models.CharField(blank=True, default="", max_length=64)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slips",
                        to="pits.pit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("voided_at__isnull", True)),
                        fields=("pit", "seq"),
                        name="uniq_active_slip_seq",
                    )
                ],
            },
        ),
    ]
